language: node_js
services:
  - xvfb
notifications:
  email: false
  slack:
    secure: Vkd2Yo1s+4/0x9+jDHQYuJV68xeoOCLNKp5VmDKUtnF4oLzaL0WnMjOG4OySqIrPcESBcUt3CUSDvsENg5Vv5zQAIkpoRskLs/B9XVYnDCquzuNWSgvC3XYesrvd6/W5WZhxJ2VJur2JKpYijyaVW8qi6fLCo9vJ1TrEsSnsqzaDFpJgsgghKQjreI1yrEOFVMybV6pTxb331Sb7yqk3IXbOzD4hXdvH0imC0pLFj1xUmabxeE32I2Soc0kRpyrKyUhUcY0gJAyKdVpqNE2iJArIOfRyrSQ3D2kplF6avjPxFM4KE36LUDRI24YHJrKklsu6fb7L6MT2+USqag71EqLyu0fqtpOqgU+bamcW3cQUu+N9ELQj6uyTzUu2/q6huLBJCF1x/AQi84vU+6JEaJelm8McRNqqw4DV60Pn9sK70yUCT7d+WiJ3qwWYm7hsAfbx4rIxDBv+3Gf1Z7NwtmlW9+9mByk6pAXVB/fOzrTB9HVnW8kJFPBR6IGIqwgIH36xdAwlE4nOyWkSgUDXDPjePNxIX4WtVrj7BW7xAhv7+Ua31hHJhua0rJi+kWJUR/PPz1B8RFDrE+nE6AlqFm7YOumpZqe8HuVzcq5wNKYQcWPhSHV/vikV1S0v5qMWVyIszhlTVeqkhR+ImQhFoUT2LdOYKg7BmWysQI0QD00=
