name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Detail the bad behavior and the steps required to duplicate it
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: What did you expect to happen when performing the action?
      placeholder: Expected behavior
      value: "Expected behavior"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of this library are you running?
      placeholder: "v0.0.0"
      value: 
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
